name: echofinds
description: "Discover your perfect match with \"AltFinder,\" the smart app that uncovers tailored alternatives for any software, product, or service, powered by Gemini AI. Simply search, filter, and save your favorites to build your ideal digital toolkit, all stored securely"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alph-ios: true
